-- MySQL Script generated by MySQL Workbench
-- 06/15/17 13:36:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema caguela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `caguela` ;

-- -----------------------------------------------------
-- Schema caguela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caguela` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `caguela` ;

-- -----------------------------------------------------
-- Table `caguela`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NOT NULL,
  `clave` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`direccion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NOT NULL,
  `callePiso` VARCHAR(255) NULL DEFAULT NULL,
  `ciudad` VARCHAR(255) NULL DEFAULT NULL,
  `codigoPostal` VARCHAR(255) NULL DEFAULT NULL,
  `comunidadAutonoma` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdentificacionFiscal` VARCHAR(255) NULL DEFAULT NULL,
  `activo` BIT(1) NOT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `vendedor` BIT(1) NOT NULL,
  `direccion_id` INT(11) NULL DEFAULT NULL,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_59sjoxx03o5h11578hamjgjcs`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `caguela`.`usuario` (`id`),
  CONSTRAINT `FK_mdw3tjolpfx2s06ts6cy65ocm`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `caguela`.`direccion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_mdw3tjolpfx2s06ts6cy65ocm` ON `caguela`.`cliente` (`direccion_id` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_59sjoxx03o5h11578hamjgjcs` ON `caguela`.`cliente` (`usuario_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `aceptado` BIT(1) NOT NULL,
  `activo` BIT(1) NOT NULL,
  `enviado` BIT(1) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `iva` FLOAT NOT NULL,
  `neto` FLOAT NOT NULL,
  `recibido` BIT(1) NOT NULL,
  `total` FLOAT NOT NULL,
  `comprador_id` INT(11) NULL DEFAULT NULL,
  `vendedor_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_3dfl9ew9n4u959lo4pw4q1wcb`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `caguela`.`cliente` (`id`),
  CONSTRAINT `FK_ooj8exqegguxb0q9d5ugl9flj`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `caguela`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_ooj8exqegguxb0q9d5ugl9flj` ON `caguela`.`pedido` (`comprador_id` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_3dfl9ew9n4u959lo4pw4q1wcb` ON `caguela`.`pedido` (`vendedor_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`tipoenvase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`tipoenvase` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`tipoenvase` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `animal` BIT(1) NOT NULL,
  `envaseCristal` BIT(1) NOT NULL,
  `envaseMetalico` BIT(1) NOT NULL,
  `envasePlastico` BIT(1) NOT NULL,
  `pescado` BIT(1) NOT NULL,
  `refrigerado` BIT(1) NOT NULL,
  `vegetal` BIT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`producto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` BIT(1) NOT NULL,
  `composicion` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `marca` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `peso` VARCHAR(255) NULL DEFAULT NULL,
  `precioSinIva` FLOAT NOT NULL,
  `tipoIVA` FLOAT NOT NULL,
  `unidades` INT(11) NOT NULL,
  `volumen` VARCHAR(255) NULL DEFAULT NULL,
  `tipoEnvase_id` INT(11) NULL DEFAULT NULL,
  `vendedor_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_7s5ks1s3976uv3c2aowwy4nlk`
    FOREIGN KEY (`tipoEnvase_id`)
    REFERENCES `caguela`.`tipoenvase` (`id`),
  CONSTRAINT `FK_m105m4xnl0qm9id27ipap8eml`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `caguela`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_7s5ks1s3976uv3c2aowwy4nlk` ON `caguela`.`producto` (`tipoEnvase_id` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_m105m4xnl0qm9id27ipap8eml` ON `caguela`.`producto` (`vendedor_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`posicion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`posicion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`posicion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL,
  `pedido_id` INT(11) NULL DEFAULT NULL,
  `producto_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_309mlqvico67ugc1n4updcptk`
    FOREIGN KEY (`producto_id`)
    REFERENCES `caguela`.`producto` (`id`),
  CONSTRAINT `FK_5n2kag9x2rfw95qqs0v4eagbf`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `caguela`.`pedido` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_5n2kag9x2rfw95qqs0v4eagbf` ON `caguela`.`posicion` (`pedido_id` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_309mlqvico67ugc1n4updcptk` ON `caguela`.`posicion` (`producto_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `caguela`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caguela`.`servicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `caguela`.`servicio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `port` INT(11) NOT NULL,
  `resultado` BIT(1) NOT NULL,
  `cliente_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_qjkj8s085k6fwikpppl8xh1sc`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `caguela`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_qjkj8s085k6fwikpppl8xh1sc` ON `caguela`.`servicio` (`cliente_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
